// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package fileop

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileopEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	UidGid      uint64
	CgroupId    uint64
	Bytes       uint64
	Flags       uint64
	Op          uint8
	Comm        [16]int8
	Path        [256]int8
	NewPath     [256]int8
	_           [7]byte
}

type fileopFdKey struct {
	_    structs.HostLayout
	Tgid uint32
	Fd   uint32
}

type fileopPathValue struct {
	_          structs.HostLayout
	Path       [256]int8
	WriteBytes uint64
	OpenFlags  uint64
	SeenFlags  uint8
	_          [7]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	fileopMapFakeEventMap       = "_fake_event_map"
	fileopMapEvents             = "events"
	fileopMapFdPaths            = "fd_paths"
	fileopMapInflightOpen       = "inflight_open"
	fileopMapInflightWrite      = "inflight_write"
	fileopMapPathHeap           = "path_heap"
	fileopProgTraceClose        = "trace_close"
	fileopProgTraceDelete       = "trace_delete"
	fileopProgTraceEnterOpen    = "trace_enter_open"
	fileopProgTraceEnterOpenat  = "trace_enter_openat"
	fileopProgTraceEnterOpenat2 = "trace_enter_openat2"
	fileopProgTraceExitOpen     = "trace_exit_open"
	fileopProgTraceExitOpenat   = "trace_exit_openat"
	fileopProgTraceExitOpenat2  = "trace_exit_openat2"
	fileopProgTraceExitWrite    = "trace_exit_write"
	fileopProgTraceLink         = "trace_link"
	fileopProgTraceLinkat       = "trace_linkat"
	fileopProgTraceMmap         = "trace_mmap"
	fileopProgTraceRename       = "trace_rename"
	fileopProgTraceRenameat     = "trace_renameat"
	fileopProgTraceRenameat2    = "trace_renameat2"
	fileopProgTraceSymlink      = "trace_symlink"
	fileopProgTraceSymlinkat    = "trace_symlinkat"
	fileopProgTraceWrite        = "trace_write"
)

// loadFileop returns the embedded CollectionSpec for fileop.
func loadFileop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fileop: %w", err)
	}

	return spec, err
}

// loadFileopObjects loads fileop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileopObjects
//	*fileopPrograms
//	*fileopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFileop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopSpecs struct {
	fileopProgramSpecs
	fileopMapSpecs
	fileopVariableSpecs
}

// fileopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopProgramSpecs struct {
	TraceClose        *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceDelete       *ebpf.ProgramSpec `ebpf:"trace_delete"`
	TraceEnterOpen    *ebpf.ProgramSpec `ebpf:"trace_enter_open"`
	TraceEnterOpenat  *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.ProgramSpec `ebpf:"trace_enter_openat2"`
	TraceExitOpen     *ebpf.ProgramSpec `ebpf:"trace_exit_open"`
	TraceExitOpenat   *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.ProgramSpec `ebpf:"trace_exit_openat2"`
	TraceExitWrite    *ebpf.ProgramSpec `ebpf:"trace_exit_write"`
	TraceLink         *ebpf.ProgramSpec `ebpf:"trace_link"`
	TraceLinkat       *ebpf.ProgramSpec `ebpf:"trace_linkat"`
	TraceMmap         *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceRename       *ebpf.ProgramSpec `ebpf:"trace_rename"`
	TraceRenameat     *ebpf.ProgramSpec `ebpf:"trace_renameat"`
	TraceRenameat2    *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSymlink      *ebpf.ProgramSpec `ebpf:"trace_symlink"`
	TraceSymlinkat    *ebpf.ProgramSpec `ebpf:"trace_symlinkat"`
	TraceWrite        *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// fileopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopMapSpecs struct {
	FakeEventMap  *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	FdPaths       *ebpf.MapSpec `ebpf:"fd_paths"`
	InflightOpen  *ebpf.MapSpec `ebpf:"inflight_open"`
	InflightWrite *ebpf.MapSpec `ebpf:"inflight_write"`
	PathHeap      *ebpf.MapSpec `ebpf:"path_heap"`
}

// fileopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileopVariableSpecs struct {
}

// fileopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileopObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopObjects struct {
	fileopPrograms
	fileopMaps
	fileopVariables
}

func (o *fileopObjects) Close() error {
	return _FileopClose(
		&o.fileopPrograms,
		&o.fileopMaps,
	)
}

// fileopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileopObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopMaps struct {
	FakeEventMap  *ebpf.Map `ebpf:"_fake_event_map"`
	Events        *ebpf.Map `ebpf:"events"`
	FdPaths       *ebpf.Map `ebpf:"fd_paths"`
	InflightOpen  *ebpf.Map `ebpf:"inflight_open"`
	InflightWrite *ebpf.Map `ebpf:"inflight_write"`
	PathHeap      *ebpf.Map `ebpf:"path_heap"`
}

func (m *fileopMaps) Close() error {
	return _FileopClose(
		m.FakeEventMap,
		m.Events,
		m.FdPaths,
		m.InflightOpen,
		m.InflightWrite,
		m.PathHeap,
	)
}

// fileopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileopObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopVariables struct {
}

// fileopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileopObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileopPrograms struct {
	TraceClose        *ebpf.Program `ebpf:"trace_close"`
	TraceDelete       *ebpf.Program `ebpf:"trace_delete"`
	TraceEnterOpen    *ebpf.Program `ebpf:"trace_enter_open"`
	TraceEnterOpenat  *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.Program `ebpf:"trace_enter_openat2"`
	TraceExitOpen     *ebpf.Program `ebpf:"trace_exit_open"`
	TraceExitOpenat   *ebpf.Program `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.Program `ebpf:"trace_exit_openat2"`
	TraceExitWrite    *ebpf.Program `ebpf:"trace_exit_write"`
	TraceLink         *ebpf.Program `ebpf:"trace_link"`
	TraceLinkat       *ebpf.Program `ebpf:"trace_linkat"`
	TraceMmap         *ebpf.Program `ebpf:"trace_mmap"`
	TraceRename       *ebpf.Program `ebpf:"trace_rename"`
	TraceRenameat     *ebpf.Program `ebpf:"trace_renameat"`
	TraceRenameat2    *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSymlink      *ebpf.Program `ebpf:"trace_symlink"`
	TraceSymlinkat    *ebpf.Program `ebpf:"trace_symlinkat"`
	TraceWrite        *ebpf.Program `ebpf:"trace_write"`
}

func (p *fileopPrograms) Close() error {
	return _FileopClose(
		p.TraceClose,
		p.TraceDelete,
		p.TraceEnterOpen,
		p.TraceEnterOpenat,
		p.TraceEnterOpenat2,
		p.TraceExitOpen,
		p.TraceExitOpenat,
		p.TraceExitOpenat2,
		p.TraceExitWrite,
		p.TraceLink,
		p.TraceLinkat,
		p.TraceMmap,
		p.TraceRename,
		p.TraceRenameat,
		p.TraceRenameat2,
		p.TraceSymlink,
		p.TraceSymlinkat,
		p.TraceWrite,
	)
}

func _FileopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fileop_arm64_bpfel.o
var _FileopBytes []byte
