name: Build & Test

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "**.go"
      - "Makefile"
      - "go.**"
      - "**.c"
      - "**.h"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "**.go"
      - "Makefile"
      - "go.**"
      - "**.c"
      - "**.h"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tensorchord/ebpf-builder:0.2.0
    steps:
      - uses: actions/checkout@v6

      - name: Build
        run: make build && make lint-ebpf

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

      - name: Test
        run: make test
